import os

configfile: "workflow/config.yaml"

# Global variables
PROJECT = config["project_dir"]
SAMPLES = config["samples"]

rule all:
    input:
        expand(
            os.path.join(PROJECT, config["results"]["fastqc"], "{sample}_fastqc.html"),
            sample=SAMPLES
        ),
        os.path.join(PROJECT, config["results"]["multiqc"], "multiqc_report.html"),
        os.path.join(PROJECT, config["results"]["counts"], "counts.txt"),
        os.path.join(PROJECT, config["results"]["deseq2"], "deseq2_results.csv")


rule fastqc:
    input:
        os.path.join(PROJECT, config["data"]["raw"], "{sample}.fastq.gz")
    output:
        os.path.join(PROJECT, config["results"]["fastqc"], "{sample}_fastqc.html"),
        os.path.join(PROJECT, config["results"]["fastqc"], "{sample}_fastqc.zip")
    threads: 4
    shell:
        "fastqc {input} --outdir " + os.path.join(PROJECT, config["results"]["fastqc"]) + " --threads {threads}"

rule trim:
    input:
        os.path.join(PROJECT, config["data"]["raw"], "{sample}.fastq.gz")
    output:
        os.path.join(PROJECT, config["results"]["trimmed"], "{sample}_trimmed.fq.gz")
    threads: 4
    shell:
        "trim_galore {input} --output_dir " + os.path.join(PROJECT, config["results"]["trimmed"]) + " --cores {threads}"

rule star_index:
    input:
        fasta = os.path.join(PROJECT, config["genome"]["fasta"]),
        gtf   = os.path.join(PROJECT, config["genome"]["gtf"])
    output:
        directory(os.path.join(PROJECT, config["star"]["genome_dir"]))
    threads: 4
    shell:
        "STAR --runMode genomeGenerate "
        "--genomeDir " + os.path.join(PROJECT, config["star"]["genome_dir"]) + " "
        "--genomeFastaFiles {input.fasta} "
        "--sjdbGTFfile {input.gtf} "
        "--runThreadN {threads}"

rule star_align:
    input:
        reads = os.path.join(PROJECT, config["results"]["trimmed"], "{sample}_trimmed.fq.gz"),
        index = os.path.join(PROJECT, config["star"]["genome_dir"])
    output:
        bam = os.path.join(PROJECT, config["results"]["star"], "{sample}_Aligned.sortedByCoord.out.bam"),
        log = os.path.join(PROJECT, config["results"]["star"], "{sample}_Log.final.out")
    threads: 4
    shell:
        "STAR --runMode alignReads "
        "--genomeDir {input.index} "
        "--readFilesIn {input.reads} "
        "--readFilesCommand zcat "
        "--outSAMtype BAM SortedByCoordinate "
        "--outFileNamePrefix " + os.path.join(PROJECT, config["results"]["star"], "{wildcards.sample}_") + " "
        "--runThreadN {threads}"

rule featurecounts:
    input:
        bams = expand(os.path.join(PROJECT, config["results"]["star"], "{sample}_Aligned.sortedByCoord.out.bam"), sample=SAMPLES),
        gtf  = os.path.join(PROJECT, config["genome"]["gtf"])
    output:
        os.path.join(PROJECT, config["results"]["counts"], "counts.txt")
    threads: 4
    params:
        strand = config["featurecounts"]["strand"]
    shell:
        "featureCounts "
        "-T {threads} "
        "-s {params.strand} "
        "-a {input.gtf} "
        "-o {output} "
        "{input.bams}"

rule multiqc:
    input:
        fastqc = expand(os.path.join(PROJECT, config["results"]["fastqc"], "{sample}_fastqc.zip"), sample=SAMPLES),
        star   = expand(os.path.join(PROJECT, config["results"]["star"], "{sample}_Log.final.out"), sample=SAMPLES)
    output:
        os.path.join(PROJECT, config["results"]["multiqc"], "multiqc_report.html")
    shell:
        "multiqc " + os.path.join(PROJECT, config["results"]["fastqc"]) + " " +
        os.path.join(PROJECT, config["results"]["star"]) + " " +
        "--outdir " + os.path.join(PROJECT, config["results"]["multiqc"])

rule deseq2:
    input:
        counts   = os.path.join(PROJECT, config["results"]["counts"], "counts.txt"),
        metadata = os.path.join(PROJECT, config["data"]["raw"], "metadata.csv")
    output:
        os.path.join(PROJECT, config["results"]["deseq2"], "deseq2_results.csv")
    shell:
        "Rscript workflow/scripts/deseq2.R {input.counts} {input.metadata} {output}"
